### ISSUE TITLE
Should iv classes coerce to character?

### ISSUE THREAD

**Issue by olivroy** [DavisVaughan/ivs#57]
should this work?

```r
ivs::iv(1:5, 7:11) |> as.character()
Error in `as.character()`:
! Can't convert `x` <iv<integer>> to <character>.
```

or only `format()` works?

**Comment by DavisVaughan** [comment]
I don't think you should be able to do `as.character()` because that typically implies there is also an `as_iv()` for character objects, and there wouldn't be one here.

Plus it is a little ambiguous - are you asking for the inner elements to become character (and still return an iv)? Or should the whole thing return a character vector?

`format()` is implemented because that is what is used for printing out the objects (at the console and in an RStudio viewer). Feel free to use that if you need a character representation for some reason. It also has slightly better printing than naively running `format()` or `as.character()` on the start/end vectors themselves due to using `iv_format()` instead.

Other than that, I don't have any plans to add an `as.character()` method

**Comment by olivroy** [comment]
Thanks!

It makes sense! 
It is just that I use `as.character()` for my custom viewers .but using `format()` works fine too!
